
const LOGIN_BY_USERNAME = 'username'
const LOGIN_BY_EMAIL = 'email'
const AVAILABLE_LOGIN_METHODS = [ LOGIN_BY_USERNAME, LOGIN_BY_EMAIL ]
const REDIS_USERNAME_INDEX = 'usernames'
const REDIS_EMAIL_INDEX = 'emails'

module.exports = {
    LOGIN_BY_USERNAME,
    LOGIN_BY_EMAIL,
    AVAILABLE_LOGIN_METHODS,
    REDIS_USERNAME_INDEX,
    REDIS_EMAIL_INDEX
}