version: '3'
services:
  miauth:
    image: anargu101/miauth:0.8.0
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks: 
      - miauth-backend
    env_file: 
      - postgres.env
    environment: 
      MIAUTH_CONFIG_FILE: miauth.config.yml
  db:
    image: postgres # use latest official postgres version
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - postgres.env
    networks: 
      - miauth-backend
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data:
networks:
  miauth-backend: