version: '3'
services:
  miauth:
    image: anargu101/miauth:0.0.3
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks: 
      - miauth-backend
    env_file: 
      - postgres.env
    environment: 
      SALT: '10'
      ACCESS_TOKEN_EXPIRATION: '86400'
      ACCESS_TOKEN_SECRET: m14uth
      REFRESH_SECRET: m14uth-f5
      PORT: 5001
      MIAUTH_CONFIG_FILE: miauth.config.yml
  db:
    image: postgres # use latest official postgres version
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - postgres.env
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: miauth-test
    #   POSTGRES_DB: miauth-test-db
    networks: 
      - miauth-backend
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data:
networks:
  miauth-backend: