version: '3'
services:
  miauth:
    image: anargu101/miauth:0.0.1
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks: 
      - backend
    environment: 
      SALT: '10'
      JWT_EXP_OFFSET: '86400'
      JWT_SECRET: m14uth
      PORT: 5001
      REDIS_PASSWORD: put_here_your_long_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      LOGIN_BY: 'username' # or 'email'
  redis:
    image: redis:5.0.6
    container_name: miauth-redis-db
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    networks: 
      - backend
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-db:
networks:
  backend: