version: '3'
services:
  miauth:
    image: anargu101/miauth:0.0.3
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks: 
      - backend
    environment: 
      SALT: '10'
      ACCESS_TOKEN_EXPIRATION: '86400'
      ACCESS_TOKEN_SECRET: m14uth
      REFRESH_SECRET: m14uth-f5
      PORT: 5001
      MIAUTH_CONFIG_FILE: miauth.config.yml
  redis:
    image: redis:5.0.6
    container_name: miauth-redis-db
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass put_here_your_long_password
    networks: 
      - backend
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-db:
networks:
  backend: