version: '3'
services:
  miauth:
    image: anargu101/miauth:0.0.1
    ports:
      - "5001:5001"
    depends_on:
      - postgre-db
    networks: 
      - backend
    environment: 
      SALT: '10'
      JWT_EXP_OFFSET: '86400'
      JWT_SECRET: m14uth
      PORT: 5001
      POSTGRES_USER: miauth
      POSTGRES_PASSWORD: m14uthdb
      POSTGRES_HOST: postgre-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: 'miauth-db'
  postgre-db:
    image: postgres:12
    restart: always
    networks: 
      - backend
    environment:
      POSTGRES_USER: miauth
      POSTGRES_PASSWORD: m14uthdb
      POSTGRES_DB: 'miauth-db'
    ports:
      - "5432:5432"
    volumes:
      - postgre-db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5002}:80"
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - postgre-db
volumes:
  postgre-db:
  pgadmin:
networks:
  backend: