version: '3'
services:
  miauth:
    image: anargu101/miauth:0.8.5
    ports:
      - "7997:7997"
    depends_on:
      - db
    networks: 
      - miauth-backend
    env_file: 
      - postgres.env
    environment:
      MIAUTH_CONFIG: |
        name: HelloMyMiauthImplementation
        public_forgot_password_url: http://localhost:7997/forgot/reset
        port: 7997
        bcrypt:
            salt: '10'
        access_token:
            secret: m14uth
            expires_in: '86400'
        refresh_token:
            enabled: true
            secret: m14uth-f5
        reset_password:
            expires_in: 600
            secret: 'm14uth-reset'
            mail_service:
                dosmj:
                    method: POST
                    endpoint: http://localhost:4000/email/send
                    payload:
                        template_name: '__required_by_dosmj_email_template_name__'
                        template_data:
                            reset_link: __dinamic__
                        email_specs:
                            subject: 'Modificar Contraseña - MiAuth'
                            to:
                                - email: __variable__
                                  name: __variable__
        user:
            username: true
            email: true
            password: true
        field_validations:
            username:
                pattern: '[a-zA-Z0-9\-\_]'
                len: [6, 72]
                invalid_pattern_error_message: 'Invalid username, it should contain between 6 and 72 alphanumeric characters.Only use alphanumeric characters.'
            email:
                pattern: ^[a-zA-Z0-9.!#$$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$$
                len: [3, 72]
                invalid_pattern_error_message: 'Invalid email, please type a correct email.'
            password:
                len: [4, 52]
                invalid_pattern_error_message: 'Invalid password. Password should contain between 4 and 52 characters'
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: 
      - postgres.env
    networks: 
      - miauth-backend
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
networks:
  miauth-backend: